coadmin/urls.py
from django.urls import path
from . import views
app_name = 'coadmin'

urlpatterns=[
    path('home',views.coadmin_home,name = 'home')
]

common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns=[
    path('',views.common_index,name = 'index'),
    path('admin',views.common_admin,name = 'admin_login'),
    path('seller',views.common_seller,name = 'seller_login'),
    path('customer',views.common_customer,name = 'customer_login')
]

customer/urls.py
from django.urls import path
from . import views
app_name = 'customer'

urlpatterns=[
    path('home',views.customer_home,name = 'home')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('',include('common.urls')),
    path('coadmin/',include('coadmin.urls')),
    path('seller/',include('seller.urls')),
]

seller/urls.py
from django.urls import path
from . import views
app_name = 'seller'

urlpatterns=[
    path('home',views.seller_home,name = 'home')
]

coadmin/models.py
from django.db import models

# Create your models here.

common/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models

# Create your models here.

seller/models.py
from django.db import models

# Create your models here.

coadmin/views.py
from django.shortcuts import render

# Create your views here.
def coadmin_home(request):
    return render(request,'coadmin_templates/home.html')

common/views.py
from django.shortcuts import render

# Create your views here.
def common_index(request):
    return render(request,'common_templates/index.html')

def common_admin(request):
    return render(request,'common_templates/admin.html')

def common_seller(request):
    return render(request,'common_templates/seller.html')

def common_customer(request):
    return render(request,'common_templates/customer.html')

customer/views.py
from django.shortcuts import render

# Create your views here.
def customer_home(request):
    return render(request,'customer_templates/home.html')

seller/views.py
from django.shortcuts import render

# Create your views here.
def seller_home(request):
    return render(request,'seller_templates/home.html')

coadmin/templates/coadmin_templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'common:index' %}"><h2>home page</h2></a>
    <a href=""><h2>approve sellers</h2></a>
    <a href=""><h2>view sellers</h2></a>
    <a href=""><h2>view customers</h2></a>
    <a href=""><h2>change password</h2></a>
</body>
</html>

common/templates/common_templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <form>
    <table>
        <tr>
            <td>Email</td>
            <td><input type="text"></td>
        </tr>
        <tr>
            <td>password</td>
            <td><input type="text"></td>
        </tr>
        <tr>
            <td><button type="submit"><a href="{% url 'coadmin:home' %}">login</a></button></td>
        </tr>
    </table> 
   </form>
</body>
</html>

common/templates/common_templates/customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form>
        <table>
            <tr>
                <td>Email</td>
                <td><input type="text"></td>
            </tr>
            <tr>
                <td>password</td>
                <td><input type="text"></td>
            </tr>
            <tr>
                <td><button type="submit"><a href="{% url 'customer:home' %}">login</a></button></td>
            </tr>
        </table> 
       </form>
</body>
</html>

common/templates/common_templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>welcome</h2>
    <a style="color:black;" href="{% url 'common:admin_login' %}"><b>admin login</b></a><br />
    <a style="color:black;" href="{% url 'common:seller_login' %}"><b>seller login</b></a><br />
    <a style="color:black;" href="{% url 'common:customer_login' %}"><b>customer login</b></a>
</body>
</html>

common/templates/common_templates/seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form>
        <table>
            <tr>
                <td>Email</td>
                <td><input type="text"></td>
            </tr>
            <tr>
                <td>password</td>
                <td><input type="text"></td>
            </tr>
            <tr>
                <td><button type="submit"><a href="{% url 'seller:home' %}">login</a></button></td>
            </tr>
        </table> 
       </form>
</body>
</html>

customer/templates/customer_templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <a href="{% url 'common:index' %}"><h2>home page</h2></a>
   <a href=""><h2>product detail</h2></a>
   <a href=""><h2>cart</h2></a>
   <a href=""><h2>my orders</h2></a>
   <a href=""><h2>change password</h2></a>
   <a href=""><h2>profile</a></h2>
</body>
</html>

seller/templates/seller_templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'common:index' %}"><h2>home page</h2></a>
    <a href=""><h2>add product</h2></a>
    <a href=""><h2>product catalogue</h2></a>
    <a href=""><h2>my orders</h2></a>
    <a href=""><h2>update stock</h2></a>
    <a href=""><h2>change password</h2></a>
    <a href=""><h2>profile</h2></a>
</body>
</html>